spring:
    application:
        name: demo
    profiles:
        active: rag-document-to-vector-store
    autoconfigure:
        exclude:
            - org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration
        # We must disable Vector Store auto-configuration because of two different EmbeddingModel beans
        # (OpenAI-Gemini and Ollama). The goal is to have two different vector collections, one for each
        # family of LLM.
    ai:
        chat:
            client:
                enabled:
                    false # Spring AI auto-configures a single ChatClient.Builder bean by default.
                    # Disabling ChatClient.Builder auto-configuration allows to manually
                    # configure multiple bean and inject them where needed.
            memory:
                repository:
                    jdbc:
                        initialize-schema: always # always, never, embedded (default)
                        schema: classpath:/schema/schema-h2.sql
        ollama:
            base-url: http://172.17.0.1:11434
            init:
                pull-model-strategy: when_missing
                timeout: 15m
                max-retries: 3
            chat:
                options:
                    model: VitoF/llama-3.1-8b-italian
                    temperature: 0.2
                    top-k: 40
                    top-p: 0.9
                    repeat-penalty: 1.1
                    presence-penalty: 1.0
            embedding:
                model: hf.co/Simone-Scannapieco/sentence-bert-base-italian-xxl-uncased-F32-GGUF
        openai:
            api-key: ${GOOGLE_AI_API_KEY}
            base-url: https://generativelanguage.googleapis.com/v1beta/openai
            chat:
                completions-path: /chat/completions
                options:
                    model: gemini-2.0-flash-lite
                    temperature: 2.0
            embedding:
                options:
                    model: gemini-embedding-001
        vectorstore:
            qdrant:
                initialize-schema: true
                host: 172.17.0.1
                port: 6334

    datasource:
        url: jdbc:h2:file:./db/chatmemory
        driver-class-name: org.h2.Driver
        username: user
        password: pwd
    h2:
        console:
            enabled: true
logging:
    level:
        org:
            springframework:
                ai:
                    chat:
                        client:
                            advisor: DEBUG